language: cpp
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
      && sudo add-apt-repository --yes ppa:team-gcc-arm-embedded/ppa
      && sudo apt-get -qq update
      && sudo apt-get install -y build-essential gdb wget debhelper
      && sudo apt-get install -y g++-multilib
      && sudo apt-get install -y libglib2.0-dev libSM-dev libxrender-dev libfontconfig1-dev libxext-dev libusb-1.0-0-dev libphonon-dev
      && sudo apt-get install -y libsdl1.2-dev
      && sudo apt-get install -y libjpeg8 libjpeg62
      && sudo apt-get install -y libudev-dev
      && sudo apt-get install -y python-lxml python-dev libxml2 libxml2-dev libxslt-dev
      && sudo apt-get install -y qt55-meta-full
      && sudo apt-get install -y gcc-arm-embedded
      ;
    else
         brew update
      && brew install qt55
      && make arm_sdk_install
      ;
    fi
before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         source /opt/qt55/bin/qt55-env.sh
         ;
    else
         export PATH="/usr/local/opt/qt55/bin:$PATH"
         ;
    fi
script:
  - make -j2 gcs all_flight

